#Study the code and determine the exact output. Also explain which lines are comments and which statements execute.
# print("1")
# # print("2")
# print("3")
# # print("4")
# print("5")
# print("6")
print("1")
# print("2")
print("3")
# print("4")
print("5")
print("6")